version: "3.9"
services:
  api:
    build:
      dockerfile: dev.Dockerfile
      context: .
      target: dev
    container_name: stash-api
    image: stash/api
    ports:
      - "8080:8080"
    working_dir: /app/stash-api
    volumes:
      - .:/app/stash-api
    command: air
    privileged: true
    networks: 
      - stash-network
networks:
  stash-network:
    driver: bridge