version: "3.9"
services:
  api:
    build:
      dockerfile: dev.Dockerfile
      context: .
      target: dev
    container_name: stash-api
    image: stash/api
    ports:
      - "8080:8080"
    volumes:
      - .:/app/stash-api