version: "3.9"

services:
  mongo:
    ports:
        - '27017:27017'
    container_name: stash-api-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    image: mongo:3.0.14
    networks: 
      - stash-network
    restart: always
    volumes:
      - ~/data/db:/data/db
