version: "3.9"

services:
  mongo:
    ports:
        - '27017:27017'
    container_name: stash-api-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # image: mangoraft/mongodb-arm  
    image: andresvidal/rpi3-mongodb3
    # platform: linux/arm/v7
    volumes:
      - /media/dalebradley/SAMSUNG/stash:/data/db
    command: mongod --repair
